_target_: navsim.agents.rap_dino.rap_agent.RAPAgent
_convert_: 'all'

config:
  _target_: navsim.agents.rap_dino.navsim_config.RAPConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False
  distill_feature: True
  pdm_scorer: True
  cache_data: False
  train_metric_cache_path: './train_metric_cache'

checkpoint_path: ''
lr: 1e-4
